title: SportCares
title-abbreviated: SportCares
description: Description
url: ""
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
collections:
    test:
        output: true
    about-sportcares:
        output: true
    children-and-youth:
        output: true
    persons-with-disabilities:
        output: true
    grants:
        output: true
    initiatives:
        output: true
    programme-and-impact:
        output: true
resources_name: media
favicon: /images/SSC.png
google_analytics: UA-38157167-4
permalink: none
baseurl: ""
defaults:
    - scope:
          path: ""
      values:
          layout: page
colors:
    primary-color: '#CC2436'
    secondary-color: '#0054A6'
    media-colors:
        - title: media-color-one
          color: '#BA0C2F'
        - title: media-color-two
          color: '#00A89C'
        - title: media-color-three
          color: '#575756'
        - title: media-color-four
          color: '#0054A6'
        - title: media-color-five
          color: '#BA0C2F'