title: SportCares
title-abbreviated: SportCares
description: Description
url: ""
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
collections:
    test:
        output: true
    about-sportcares:
        output: true
    children-and-youth:
        output: true
    persons-with-disabilities:
        output: true
    grants:
        output: true
    initiatives:
        output: true
    programme-and-impact:
        output: true
resources_name: media
favicon: /images/SSC.png
google_analytics: UA-38157167-4
permalink: none
baseurl: ""
defaults:
    - scope:
          path: ""
      values:
          layout: page
